### ISSUE TITLE
Support for ng-change on pagination

### ISSUE THREAD

**Issue by ptink** [samu/angular-table#102]
A useful feature of angular-bootstrap pagination is that you can specify a function to run on ng-change of the currentPage model, which helps when attempting to change the $stateParams to reflect the current page in the url for example. Is there any chance of getting similar functionality in angular-table?

**Comment by samu** [comment]
@ptink i'm not actively working on this directive any longer, so this functionality will not come any time soon. A less optimal but working solution would be to `$watch` the `currentPage` attribute on your config object.
