### ISSUE TITLE
Mention that angular-table has to be added as dependency

### ISSUE THREAD

**Issue by jahrralf** [samu/angular-table#103]
Hi, 

Neither from the readme nor from the examples it is visible that angular-table has to be added as reference to the angular module:

        angular.module("angular-table-example", ["angular-table", ...]);

Please add this! Thanks.

Ralf

**Comment by samu** [comment]
Hi Ralf,
thanks for raising this concern. The example code assumes some basic knowledge of how angular works. Using a 3rd party module in angular always requires you to add it as a dependency, and i don't think it makes sense to document that for every module. The examples on the demo page are only showing the essential code, all boiler plate code (setting up main controller etc.) has been left out for sake of simplicity.
