### ISSUE TITLE
at-title not rendering the dynamic data

### ISSUE THREAD

**Issue by bhuvaneshCES** [samu/angular-table#104]
@samu When I am trying to use the **ng-repeat to render the rows dynamically** like

`<td ng-repeat="column in columns" at-attribute="{{column.text}}" at-title="{{column.value}}"></td>`

and my columns be like

> $scope.columns = [
 {value: 'firstValue', text: 'Selected'}
]

The **at-title is not rendering** the string on the angular-table but it have a string in it when I checked it by inspecting.

and my row rendering is working as expected but not sure why the at-title is not displayed.

Going through the repo does not help me out finding where the issue is exactly.

It would be great if we get the solution as soon as possible.

Thanks in advance.

**Comment by samu** [comment]
Hi @bhuvaneshCES, i'm afraid your requirements exceed the capabilities of this directive. Having dynamic titles has been requested before (see #18 for example), but you can't do it out of the box with `angular-table`.
