### ISSUE TITLE
Make "first" / "last" buttons customizable

### ISSUE THREAD

**Issue by PhilippSchreiber** [samu/angular-table#42]
I'm building an app with 12 languages and cannot translate the buttons. The buttons should be customizable...

Perhaps I can do it and start a pull request...

**Comment by samu** [comment]
I currently don't have time to work on this but i'd defenitely accept a pull request. I'll be thankful if you provide tests as well.

**Comment by thotty** [comment]
I did a little change in my [fork](https://github.com/thotty/angular-table):
-  coffee/configuration/scope_config_wrapper.coffee
-  coffee/directives/at_pagination.coffee
-  coffee/directives/pagination/pagination_template.coffee

Now we can pass to grid config the object with (key: 'value default'):
-  `stepBack: '‹'`
-  `stepAhead: '›'`
-  `jumpBack: '«'`
-  `jumpAhead: '»'`
-  `first: 'First'`
-  `last: 'Last`

What you think about it?
Do you accept one PR to change this?

**Comment by samu** [comment]
Thanks @thotty 

Did you test it? What code is required to override the default labels with custom ones?

**Comment by thotty** [comment]
I runned `karma start` (CLI) and passed OK, but when I started the browser he changes the order of paginator labels and fail... I don't understand why this occurs.

Before open a PR, how do you exec the command to compile all CoffeeScripts to dist folder?

**Comment by samu** [comment]
Simply run grunt, without any additional params:
`grunt`

**Comment by thotty** [comment]
Great! Right now I'm traveling, I go back next week. When I return I will
run and if oks, I will send you a PR. Thanks

On 05:17, Tue, Aug 18, 2015 Samuel Mueller <notifications@github.com> wrote:

> Simply run grunt, without any additional params:
> grunt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samu/angular-table/issues/42#issuecomment-132116712>.
>
-- 
var signature = {
    name: *'Sósthenes Ramos Prado Neto'**,*
    mobile: *'+55 61 9811-7559',*
    skype: *'sosthenes.neto'*
};

**Comment by linyatis** [comment]
Hey @thotty and @samu, do you have any update about this issue?
I need to customize the buttons in my app, so I'm very interested to put this to work =)
Do you need any help?

**Comment by thotty** [comment]
@linyatis, tudo bom?..
Velho, estou um pouco enrolado aqui no trabalho e não pude dar continuidade.. Eu  fiz um  [fork](https://github.com/thotty/angular-table) e modifiquei umas paradas, mas fiquei de testar...

@samu, 
I'm sorry for the delay with this.
I'm busy here at work... But as soon as I can, I'll continue with this issue. :D

**Comment by linyatis** [comment]
@thotty, can I help you with anything?

**Comment by thotty** [comment]
@linyatis, you can't speak portugese? :)
I finished my changes.. I'll do a PR and you can use if you desire..

@samu, after a PR I will coding to `paginationLabels` accepts a HTML statement. OK?

**Comment by thotty** [comment]
[PR sent](https://github.com/samu/angular-table/pull/62)!

**Comment by linyatis** [comment]
>@linyatis, you can't speak portugese? :)

@thotty, I'm talking in English so @samu could join us if he wants =)

**Comment by thotty** [comment]
@linyatis, goood idea! My bad :smile:

**Comment by samu** [comment]
Fixed with #62, thanks @thotty
