### ISSUE TITLE
pagination not resettng

### ISSUE THREAD

**Issue by bigerock** [samu/angular-table#48]
great table btw. thanks for developing it.

i've found that when the list that the table is bound to updates, it doesn't reset the pagination to the beginning. i've changed the code locally to reflect a fix for this:

line 595 in the update function
if (reset) w.setCurrentPage(0);

and line 635:
scope.$watch($attributes.atList, function () {
return update(true);
}

**Comment by samu** [comment]
please open a pull request for this. remember to work on the coffee script code and not the compiled js.

**Comment by samu** [comment]
By the way, please note that this behaviour is intentional. If you are going to create a PR, there should be a configuration option to specify whether the table jumps to the first page or stays where it is.
