### ISSUE TITLE
get current display number

### ISSUE THREAD

**Issue by bigerock** [samu/angular-table#49]
i'm looking to display a page count like when you're on page 2 and you want to display 5-10 of 100. 

any methods here for this?

**Comment by samu** [comment]
please check out the examples: http://samu.github.io/angular-table/examples/examples.html

does that cover your question?

**Comment by bigerock** [comment]
i apologize that i may not have worded my question properly...

i want to be able to show the status of the pagination in terms of count... when you're on page 2 and have 100 results, and are paging by 5, then i want to be able to show '5-10 of 100' on the page, etc.

**Comment by samu** [comment]
There's no out of the box solution for this, but you can access the current page as shown in the `Interactive Example` on the demo pages.

You define a `at-config="config"` attribute which sets up a dual-binding to your scope variable `config`, which will contain a `currentPage` attribute.

Hope that helps.

**Comment by bigerock** [comment]
that does help. just what i needed. thank you!
