### ISSUE TITLE
Not able to use angular date filter with it

### ISSUE THREAD

**Issue by wasimakram-mulla** [samu/angular-table#57]
I am having my object as 
eg. 
Obj={
"id":4,
"userName":"Test",
"submittedOn":1440486440000
}

Previously before using this plugin I was able to use the builtin Date Filter of Angular.
Please provide some solution for the same.

![capture](https://cloud.githubusercontent.com/assets/6120192/9466031/3b0ea972-4b4f-11e5-80ce-9836e239a8e6.PNG)

**Comment by samu** [comment]
@wasimakram-mulla you should be able to access the element of each row with {{item}}.

**Comment by wasimakram-mulla** [comment]
Thanks a Ton Samuel..

I just had to remove at-implicit and change a bit structure and using item is was done.

Thanks again :) +1:
