### ISSUE TITLE
Is the sorting of links within a <td> element supported?

### ISSUE THREAD

**Issue by deciob** [samu/angular-table#60]
I have a table like this:

```html
 <table at-table at-paginated at-list="filteredList" at-config="config">
  	<thead>
    </thead>
    <tbody>
      <tr>
        <td at-title="user"><a ng-href="#" at-attribute="user" at-implicit></a></td>
        <td at-implicit at-attribute="score" at-sortable></td>
        <td at-implicit at-attribute="lastActivity" at-sortable></td>
      </tr>
    </tbody>
  </table>
```

and all works fine, but I am struggling to make the user column sortable.

This does not work:

```html
<td at-title="user"><a ng-href="#" at-attribute="user" at-implicit at-sortable></a></td>
```

And this only allows sorting the column once:

```html
<td at-title="user" at-sortable><a ng-href="#" at-attribute="user" at-implicit></a></td>
```

Is this just not supported or am I doing something wrong? Any help appreciated, thanks.

**Comment by samu** [comment]
@deciob please note that you can use `at-attribute` and `at-implicit` only in the `<td>`-element. Try changing this line

`<td at-title="user" at-sortable><a ng-href="#" at-attribute="user" at-implicit></a></td>`

to this

`<td at-title="user" at-attribute="user" at-sortable><a ng-href="#">{{item.user}}</a></td>`

**Comment by deciob** [comment]
@samu thank you very much for this. It worked correctly.

**Comment by UnnamedSong** [comment]
@samu Thank you very much. :)
This is exactly what I'm wondering.
Very helpful.
