### ISSUE TITLE
Limit the maximum visible buttons for pagination

### ISSUE THREAD

**Issue by crashbtz** [samu/angular-table#63]
Hi,

firstable thanks for this plugin, it's very usefull for ou project.
We wanted to know if it's possible to make an improvement to limit the number of visible buttons like in angular bootstrap pagination:

![pagination](https://cloud.githubusercontent.com/assets/4550542/10280310/832dc39a-6b6c-11e5-8918-c5e696b89c71.png)

Because we have a table with a lot of entries and we have like 50 pages so it's not very beautiful to have 50 buttons.

Thank you

**Comment by samu** [comment]
Yes it is possible, please check out the demo.

**Comment by crashbtz** [comment]
indeed, RTFM @crashbtz :)

thanks
