### ISSUE TITLE
How to get attribute array from list

### ISSUE THREAD

**Issue by thanhrossi** [samu/angular-table#66]
I have one list, and i just want list ronAdSlotSegment from ronAdSlotSegments array. Please help me
[
    {
        "id": 1,
        "libraryAdSlot": {
            "name": "thanhxczc",
            "visible": false,
            "libType": "display",
            "publisher": {
                "id": 2,
                "company": "dtag",
                "enabledModules": [
                    "MODULE_ANALYTICS",
                    "MODULE_DISPLAY",
                    "MODULE_VIDEO_ANALYTICS"
                ],
                "username": "sieunhan"
            },
            "id": 2,
            "width": 123,
            "height": 23,
            "autoFit": true,
            "passbackMode": "peerpriority"
        },
        "ronAdSlotSegments": [
            {
                "id": 52,
                "ronAdSlot": null,
                "segment": {
                    "id": 52,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "xzcxzc"
                }
            },
            {
                "id": 53,
                "ronAdSlot": null,
                "segment": {
                    "id": 3,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "zxc"
                }
            },
            {
                "id": 54,
                "ronAdSlot": null,
                "segment": {
                    "id": 4,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "l[l["
                }
            }
        ]
    },
    {
        "id": 2,
        "libraryAdSlot": {
            "name": "thanhxxxxczc",
            "visible": false,
            "libType": "display",
            "publisher": {
                "id": 2,
                "company": "dtag",
                "enabledModules": [
                    "MODULE_ANALYTICS",
                    "MODULE_DISPLAY",
                    "MODULE_VIDEO_ANALYTICS"
                ],
                "username": "sieunhan"
            },
            "id": 2,
            "width": 123,
            "height": 23,
            "autoFit": true,
            "passbackMode": "peerpriority"
        },
        "ronAdSlotSegments": [
            {
                "id": 52,
                "ronAdSlot": null,
                "segment": {
                    "id": 52,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "xzcxzc"
                }
            },
            {
                "id": 53,
                "ronAdSlot": null,
                "segment": {
                    "id": 3,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "zxc"
                }
            },
            {
                "id": 54,
                "ronAdSlot": null,
                "segment": {
                    "id": 4,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "l[l["
                }
            }
        ]
    }
]

**Comment by samu** [comment]
@thanhrossi I don't understand, please clarify, thanks.

**Comment by thanhrossi** [comment]
[
    {
        "id": 1,
        "libraryAdSlot": {
            "name": "thanhxczc",
            "visible": false,
            "libType": "display",
            "publisher": {
                "id": 2,
                "company": "dtag",
                "enabledModules": [
                    "MODULE_ANALYTICS",
                    "MODULE_DISPLAY",
                    "MODULE_VIDEO_ANALYTICS"
                ],
                "username": "sieunhan"
            },
            "id": 2,
            "width": 123,
            "height": 23,
            "autoFit": true,
            "passbackMode": "peerpriority"
        },
        "ronAdSlotSegments": [
            {
                "id": 52,
                "ronAdSlot": null,
                "segment": {
                    "id": 52,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "xzcxzc"
                }
            },
            {
                "id": 53,
                "ronAdSlot": null,
                "segment": {
                    "id": 3,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "zxc"
                }
            },
            {
                "id": 54,
                "ronAdSlot": null,
                "segment": {
                    "id": 4,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "l[l["
                }
            }
        ]
    },
    {
        "id": 2,
        "libraryAdSlot": {
            "name": "thanhxxxxczc",
            "visible": false,
            "libType": "display",
            "publisher": {
                "id": 2,
                "company": "dtag",
                "enabledModules": [
                    "MODULE_ANALYTICS",
                    "MODULE_DISPLAY",
                    "MODULE_VIDEO_ANALYTICS"
                ],
                "username": "sieunhan"
            },
            "id": 2,
            "width": 123,
            "height": 23,
            "autoFit": true,
            "passbackMode": "peerpriority"
        },
        "ronAdSlotSegments": [
            {
                "id": 52,
                "ronAdSlot": null,
                "segment": {
                    "id": 52,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "xzcxzc"
                }
            },
            {
                "id": 53,
                "ronAdSlot": null,
                "segment": {
                    "id": 3,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "zxc"
                }
            },
            {
                "id": 54,
                "ronAdSlot": null,
                "segment": {
                    "id": 4,
                    "publisher": {
                        "id": 2,
                        "company": "dtag",
                        "enabledModules": [
                            "MODULE_ANALYTICS",
                            "MODULE_DISPLAY",
                            "MODULE_VIDEO_ANALYTICS"
                        ],
                        "username": "sieunhan"
                    },
                    "name": "l[l["
                }
            }
        ]
    }
]
Yup. I want get array item from list . Example: how to get  segment.name from
