### ISSUE TITLE
How to use custom headers ?

### ISSUE THREAD

**Issue by drazik** [samu/angular-table#69]
Hello,

Thanks for this great directive. It works pretty well. But I have a use case in which the headers of my table can't be simply my object's properties camelCased. Is there a way I can provide custom headers ?

Thank you very much

**Comment by samu** [comment]
Hi @drazik & thanks for the compliment. Yes, you should be able to do it like this:

`at-title="custom title"`

**Comment by samu** [comment]
You can also look on the examples page (Tab "Customizing The Header"): 

http://samu.github.io/angular-table/examples/examples.html

**Comment by drazik** [comment]
That's absolutely perfect ! Thank you very much !!

I close the issue, but I have a little question for you : why don't you put the directive on npm ?

Thanks again for the work and you (very fast) answer :)

**Comment by samu** [comment]
The reason it isn't on npm is beacause it is already published through bower. But you're right, i've seen a lot of projects that have been managing their front end dependencies through npm lateley, so i should probably take the step forward and release it to npm. Thanks for the hint anyways.

**Comment by drazik** [comment]
Yeah I think such a good package must be on npm :)

**Comment by csaftoiu** [comment]
I had this same question! I didn't see the examples link at first - maybe you can put it in the body of the README.md? 

In any case, thanks for this simple & easy-to-use directive. I was about to implement the same thing but I figured somebody else must have already done it. I tried ngTable but it didn't work right off the bat so... here I am!
