### ISSUE TITLE
How can Sort a "column" from controller in config

### ISSUE THREAD

**Issue by maherAshori** [samu/angular-table#73]
Hi
Thx for this module;
i need to sort a column from my angular controller by "Desc" & "Asc"

        $scope.config = {
            itemsPerPage: 10,
            maxPages: 3,
            sortContext: "desc", //<=== is it right?
            currentPage: 0,
            fillLastPage: false
        }

**Comment by samu** [comment]
Should be correct, let me know if it doesn't work
