### ISSUE TITLE
Can I get callback when click row.

### ISSUE THREAD

**Issue by jinjongch** [samu/angular-table#75]
How are you.
Your plugin is very useful.
However, I hope get callback when click any row.
How to can I get selected item?
Help me.
Thanks. Regards.

**Comment by pelicanorojo** [comment]
Hi!

If you see this code: 
https://github.com/samu/angular-table/blob/master/coffee/directives/table/setup/standard_setup.coffee

You will discover that your rows are generated by a ng-repeat directive, and that you will have available the item var for access your iterated data.

For instance, have this html (< and > replaced with [ and ]):

[table  class="table table-striped table-bordered"
        at-table at-paginated at-list="account.mergedRacsIdsData" at-config="account.tableConfig"]
        [thead][/thead]
        [tbody]
          [tr ng-click="account.showSignupPending(item)"]
            [td at-implicit at-attribute="racsId" at-title="First Name"][/td]
            [td at-implicit at-attribute="mol" at-title="Last Name"][/td]
            [td at-implicit at-attribute="myVitals" at-title="Email"][/td]
            [td at-implicit at-attribute="mol" at-title="Phone"][/td]
            [td at-implicit at-attribute="myVitals" at-title="Mobile"][/td]
          [/tr]
        [/tbody]
      [/table]
      [at-pagination ng-if="account.mergedRacsIdsData.length ] account.tableConfig.itemsPerPage" at-list="account.mergedRacsIdsData" at-config="account.tableConfig"][/at-pagination]

And when click a row, I have my item with the item data I need, in my case, racsId functions as an id.

I hope this help.

But, you shouldn't do reverseengineering, if samu just document and fix this,
access item will become reliable.
