### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by waar19** [samu/angular-table#76]
I can´t make the pagination work...Please help me  with the pagination. Thanks

**Comment by samu** [comment]
What's the problem?

**Comment by ropherpanama** [comment]
For me all works fine, just I like to show an Index column. With Angular I use <th scope="row">{{ $index + 1 }}</th>, how can show this using your module?

**Comment by samu** [comment]
have you tried using `$index`? It might work, im not exactly sure.

**Comment by ropherpanama** [comment]
Huum I tried, but not work properly.
If I have an array with 20 items and a grid that shows 5 per page, the $index goes from 1 to 5 in each page, should be 1 to 5 in the 1st page, 6 to 10 in the 2nd, etc. Any idea or fix?

**Comment by samu** [comment]
Try this:

```
$scope.calculateIndex = function() {
  $scope.config.currentPage * $scope.config.itemsPerPage + $index
}
```
