### ISSUE TITLE
Multiple tables on one page

### ISSUE THREAD

**Issue by brycehewett** [samu/angular-table#77]
I'm using at-table inside of an ng-repeat and when I try to use the pagination, it paginates all the tables on the page. Is there a way to only paginated the desired table?

**Comment by samu** [comment]
it should be possible if you use a separate object for `at-config` for every table

**Comment by brycehewett** [comment]
How would I achieve that? The tables are displayed based on the data from the database, so I don't think I'd be able to create a config for each in the controller. I tried doing `at-config="{itemsPerPage: 1}"` with no luck.

**Comment by samu** [comment]
i think you could iterate over the list as soon as it is loaded, and manually create a config object for each entry. i know it's ugly and tedious, but i can't think of an other way right now.
