### ISSUE TITLE
Natural Sorting Functionality?

### ISSUE THREAD

**Issue by TanakritBenz** [samu/angular-table#78]
Is there a way to achieve natural sorting order? 
Right now, say we have a list `['A1', 'A2', ... , 'A10', 'A11']`, it will get sorted as `['A1', 'A10', 'A11', 'A2', ...]`. 

I look in the file and it seems like the sorting is done around [here.](https://github.com/samu/angular-table/blob/c97b53fbaa6a1ec3f5c373af6e808b8fbec18d21/coffee/directives/table/setup/paginated_setup.coffee#L28) Perhaps you can shed some light on how I can implement such thing into the module.

Thanks :)

**Comment by samu** [comment]
You'd have to specify your own filter in order to do this kind of sorting. Please have a look at #40. You can register your own filter in angular, and then reference it on your config object through the `.orderBy` attribute. Let me know if it works.

**Comment by TanakritBenz** [comment]
Thank you for your quick response! Yes, injecting a custom filter to `orderBy` works.

Here's the [example](https://jsfiddle.net/Tanakrit/ob5s7v78/1/) for future reference in case anyone runs into this topic.
