### ISSUE TITLE
Not working - Throwing Injector Error

### ISSUE THREAD

**Issue by funzeye** [samu/angular-table#81]
Error: [$injector:unpr] http://errors.angularjs.org/1.2.29/$injector/unpr?p0=%24templateRequestProvider%20%3C-%20%24templateRequest%20%3C-%20%24route

**Comment by samu** [comment]
It's hard to provide a solution with such little information given. I'm not sure how this is related to this directive.

**Comment by funzeye** [comment]
Ya sorry,
Not 100% sure but seems to be due to using angular-route library - That's a guess on my part just seeing the rword route appears in above error message.

Running a pretty basic angular 1.x app with angular route library also used.
As soon as I added this angular table library this error started appearing in console and nothing loaded, page was blank basically. Remove the library - everything worked again. I didn't even add any of the code, just loaded the file in the header <script > area.

The above was literally the only error message provided. Sorry I cant be of more help. If you don't think its an issue then feel free to close.

**Comment by samu** [comment]
So your error message

`Unknown provider: $templateRequestProvider <- $templateRequest <- $route`

is saying you don't have a provider for the `$templateRequest` service. `angular-table` doesn't depend on this, and i don't see why it would cause the service suddenly not to be found. Are you sure you have set up your dependencies correctly? Also, it would easier if you could provide a plunker or a demo project which reproduces this problem.
