### ISSUE TITLE
Set custom sort icon

### ISSUE THREAD

**Issue by RodolfoSilva** [samu/angular-table#83]
How can I set a custom icon for sort column?

```html
<i class="fa fa-angle-down" aria-hidden="true"></i>
```
```html
<i class="fa fa-angle-up"></i>
```

**Comment by samu** [comment]
You should be able to implement a function called `getSortIcon` on your scope. Here's how its implemented internally: https://github.com/samu/angular-table/blob/0c18e15b24098c86ff287b0a633f2dc19001417f/coffee/directives/table/table.coffee#L41
