### ISSUE TITLE
Custom Pagination element

### ISSUE THREAD

**Issue by ketsugi** [samu/angular-table#84]
I'm currently using this directive to display a table which potentially may have many, many pages (my current sample data has 50 pages of table rows).

Is it possible to create a custom pagination element (eg condensing the page numbers, or using a select dropdown) that can control which rows are being displayed in the table?

**Comment by samu** [comment]
This is already possible with this implementation. Check out the [examples](http://samu.github.io/angular-table/examples/examples.html)

**Comment by ketsugi** [comment]
Thanks, I missed the `maxpages` property in the config. Sorry to bother you.
