### ISSUE TITLE
Rotate pagination

### ISSUE THREAD

**Issue by sandeshds** [samu/angular-table#86]
Is it possible to rotate the pagination upon clicking on a particular page or clicking next ? 
Example : look at the "rotate" option in pagination here ,  https://angular-ui.github.io/bootstrap/

**Comment by samu** [comment]
Yes, please take a look at the [examples](http://samu.github.io/angular-table/examples/examples.html), theres a `maxPages` option.

**Comment by sandeshds** [comment]
Hi , 

Sorry if i did not put my point across correctly. I want the navigation to change based on a page click. 

Say my max pages is set to 5, with total number of pages being 7. The pages shown are [1,2,3,4,5].
And now i click on page 4. Then the pages displayed should be [2,3,4,5,6]. The link above , with the rotate option set has this behaviour. Where as the demo examples do not.

**Comment by samu** [comment]
Ah i see. No thats not possible currently i'm afraid
