### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by Sopheakmorm** [samu/angular-table#87]
Hi guys,

May I add horizontal scrollbar for angular-table ?

Thank you !

**Comment by samu** [comment]
What do you mean, in the form of a pull request?

**Comment by Sopheakmorm** [comment]
hi,
I want to make my angular-table with Horizontal/Vertical Scroll bar when the data has over the page
thank you

**Comment by samu** [comment]
Sure, go ahead

**Comment by Sopheakmorm** [comment]
How can I make it ?

**Comment by samu** [comment]
Here, i prepared something for you, [check it out](http://lmgtfy.com/?q=how+to+make+an+html+element+horizontally+scrollable).
