### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by markus138** [samu/angular-table#90]
Hello, could you release the project on npm aswell?

**Comment by samu** [comment]
@markus138 Hey there, sorry for the long delay. Is an npm release still needed? I'm not very familiar with releasing packages on npm and am not sure if i'll find time to look into it.

**Comment by markus138** [comment]
if you find the time it would be nice, but personally I can work with github directly

**Comment by theantichris** [comment]
With the incline of NPM usage over Bower I think offering a NPM package would be useful.

**Comment by theantichris** [comment]
@samu It looks like you did most of the work already thanks to using Gulp. Just make sure the dependencies for the package are added to package.json and publish.

https://gist.github.com/coolaj86/1318304

**Comment by theantichris** [comment]
@samu I set the package.json up for you.

#97

**Comment by brunowego** [comment]
The package exists on npm registry:

```sh
npm info angular-table
```

But [postinstall](https://github.com/samu/angular-table/blob/master/package.json#L23) break if not have installed bower.

**Comment by theantichris** [comment]
@brunowego Done.
