### ISSUE TITLE
How you make the header column width fixed

### ISSUE THREAD

**Issue by dropyghost** [samu/angular-table#92]
in the example.

http://samu.github.io/angular-table/examples/examples.html

When you change between pages the columns width size doesnt change

But in your beginner example after 4th step the column width change between each page.

http://samu.github.io/angular-table/walkthrough/4.html

So what is the difference?

**Comment by samu** [comment]
@dropyghost the width of table columns can be set through css: https://css-tricks.com/fixing-tables-long-strings/
