### ISSUE TITLE
 Cant get click event

### ISSUE THREAD

**Issue by dropyghost** [samu/angular-table#94]
if I put the image on the table row doesnt respond to the click event.

I use jquery `$('.car-center').click()` to respond click events

If I put the same code outside works ok

`<img src="/GTracker/Content/center-icon.png" class="car-center" id="center-2546" data-x="123.910467" data-y="12.978933">`

http://i.stack.imgur.com/PcXiz.png

**Comment by samu** [comment]
@dropyghost why are you using jquery to handle the click event? Since you're using angular, you should be able to do this with `ng-click`.

I'll close this as this doesn't seem to be related directly to this directive.
