### ISSUE TITLE
Table does not show values when the column title has space

### ISSUE THREAD

**Issue by sajeetharan** [samu/angular-table#95]
Table does not show values when the column title has space

I am not able to bind data which is something like this,

[{"id":0,"Ship  new_Mode":"Delivery Truck","avg_Profit":235.29},{"id":1,"Ship  new_Mode":"Express Air","avg_Profit":149.98},{"id":2,"Ship  new_Mode":"Regular Air","avg_Profit":176.19}]

is an unexpected token at column 13 of the expression [item.Order_ Priority] starting at [Priority].

**Comment by samu** [comment]
@sajeetharan i don't understand. Could you please provide a code example?

**Comment by sajeetharan** [comment]
@samu  Check this plunker http://plnkr.co/edit/scG4nI5Zy7pOgAPXEIoG?p=preview  where avg _Sales has a space

**Comment by sajeetharan** [comment]
@samu  were you able to check on this?

**Comment by samu** [comment]
Hey @sajeetharan, sorry for the delay.

I'm afraid you're trying to use this directive in a way it was not intended to be used. Having a dynamic amount of columns is not supported. Every column you want to used must be explicitly declared, hence you'd need a specific declaration for the avarage sales column.

`"avg _Sales"` is not going to work either with a space. You'll have to transform your data beforehand and remove that space (or fix the API where this data is coming from in the first place).

**Comment by sajeetharan** [comment]
Yes i have fixed that way, thanks for the reply
